pipeline {
    agent { label 'windows' }
    environment {
        API_DIR = 'server/'
        JwtSettings__Secret = credentials('jwt-key')
        ConnectionStrings__Cinema = credentials('test-conn')
        JwtSettings__Issuer = "CinemaApi"
        JwtSettings__Audience = "CinemaClient"
    }

    stages {
        stage('build') {
            steps {
                dir(env.API_DIR) {
                    bat 'dotnet build Cinema.slnx -c Release'
                }
            }
        }

        stage('Test') {
            steps {
                dir(env.API_DIR) {
                    powershell 'Remove-Item -Recurse -Force */TestResults -ErrorAction SilentlyContinue'
                    bat 'dotnet test Cinema.slnx -c Release --no-build --logger "junit;LogFilePath=TestResults/{assembly}.junit.xml" --logger trx'
                }
            }
        }
    }

    post {
        always {
            dir(env.API_DIR) {
                junit allowEmptyResults: true, testResults: '**/TestResults/*.junit.xml'
                archiveArtifacts allowEmptyArchive: true, artifacts: '**/TestResults/*.trx'
            }
        }
    }
}