// <auto-generated />
using System;
using Cinema.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cinema.Data.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    partial class CinemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cinema.Data.Entities.Cinemas", b =>
                {
                    b.Property<int>("Cinema_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cinema_Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CinemaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<short>("City")
                        .HasColumnType("smallint");

                    b.HasKey("Cinema_Id");

                    b.HasIndex("CinemaName")
                        .IsUnique();

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Cinema_Id = 1,
                            Address = "Av. Aviación 3800, San Juan de Ocotán, 45019",
                            CinemaName = "FAWO Guadalajara",
                            City = (short)35
                        },
                        new
                        {
                            Cinema_Id = 2,
                            Address = "133, P.º de los Héroes 9550, Zona Urbana Rio Tijuana, 22320",
                            CinemaName = "FAWO Tijuana",
                            City = (short)3
                        },
                        new
                        {
                            Cinema_Id = 3,
                            Address = "Perif. Luis Echeverría 1474, Lourdes, 25070",
                            CinemaName = "FAWO Saltillo",
                            City = (short)15
                        },
                        new
                        {
                            Cinema_Id = 4,
                            Address = "Granada, Miguel Hidalgo, 11520",
                            CinemaName = "FAWO Ciudad de México",
                            City = (short)14
                        });
                });

            modelBuilder.Entity("Cinema.Data.Entities.Movies", b =>
                {
                    b.Property<int>("Movie_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Movie_Id"));

                    b.Property<short>("DurationMinutes")
                        .HasColumnType("smallint");

                    b.Property<byte>("Genre")
                        .HasColumnType("tinyint");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Movie_Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Movie_Id = 1,
                            DurationMinutes = (short)157,
                            Genre = (byte)8,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNTU1MzgyMDMtMzBlZS00YzczLThmYWEtMjU3YmFlOWEyMjE1XkEyXkFqcGc@._V1_FMjpg_UY2902_.jpg",
                            Rating = (byte)2,
                            Synopsis = "Adaptation of the first of J.K. Rowling's popular children's novels about Harry Potter, a boy who learns on his eleventh birthdaythat he is the orphaned son of two powerful wizards and possesses unique magical powers of his own. He is summoned from his life as an unwantedchild to become a student at Hogwarts, an English boarding school for wizards. There, he meets several friends who become his closest allies andhelp him discover the truth about his parents' mysterious deaths.",
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Movie_Id = 2,
                            DurationMinutes = (short)150,
                            Genre = (byte)8,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTc0NTUwMTU5OV5BMl5BanBnXkFtZTcwNjAwNzQzMw@@._V1_QL75_UY562_CR0,0,380,562_.jpg",
                            Rating = (byte)2,
                            Synopsis = "During the World War II bombings of London, four English siblings are sent to a country house where they will be safe. One day Lucy (Georgie Henley)finds a wardrobe that transports her to a magical world called Narnia. After coming back, she soon returns to Narnia with her brothers, Peter (William Moseley)and Edmund (Skandar Keynes), and her sister, Susan (Anna Popplewell). There they join the magical lion, Aslan (Liam Neeson), in the fight against the evil White Witch, Jadis (Tilda Swinton).",
                            Title = "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe"
                        },
                        new
                        {
                            Movie_Id = 3,
                            DurationMinutes = (short)134,
                            Genre = (byte)4,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BOTRkMDlmZWEtMzQyYy00YzgyLTgwM2QtNzgxYmIwNGVlYmJlXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg",
                            Rating = (byte)4,
                            Synopsis = "In 1977, paranormal investigators Ed (Patrick Wilson) and Lorraine Warren come out of a self-imposed sabbatical to travel to Enfield,a borough in north London. There, they meet Peggy Hodgson, an overwhelmed single mother of four who tells the couple that something evil is in her home.Ed and Lorraine believe her story when the youngest daughter starts to show signs of demonic possession. As the Warrens try to help the besieged girl,they become the next targets of the malicious spirit.",
                            Title = "The Conjuring 2"
                        },
                        new
                        {
                            Movie_Id = 4,
                            DurationMinutes = (short)117,
                            Genre = (byte)6,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BNTI4ZWQ5YjYtMmYwMy00OWFmLWFmNDYtZGNlNWMxNTllZjc4XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg",
                            Rating = (byte)3,
                            Synopsis = "Noah has to leave her town, boyfriend and friends behind and move into the mansion of her mother's new rich husband. There she meets Nick,her new stepbrother. She soon discovers that, behind the image of a model son, Nick is hiding something.",
                            Title = "My Fault"
                        },
                        new
                        {
                            Movie_Id = 5,
                            DurationMinutes = (short)106,
                            Genre = (byte)2,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTQ1OTU0ODcxMV5BMl5BanBnXkFtZTcwOTMxNTUwOA@@._V1_QL75_UX380_CR0,20,380,562_.jpg",
                            Rating = (byte)4,
                            Synopsis = "When John Bennett (Mark Wahlberg) was a little boy, he made a wish that Ted (Seth MacFarlane), his beloved teddy bear, would come alive.Thirty years later, foul-mouthed Ted is still John's constant companion, much to the chagrin of Lori (Mila Kunis), John's girlfriend. Though Lori'sdispleasure is exacerbated by the pair's constant consumption of beer and weed, she's not the one who's most disappointed with John; it may takethe intervention of John's boyhood toy to help him grow up at last.",
                            Title = "Ted"
                        });
                });

            modelBuilder.Entity("Cinema.Data.Entities.Roles", b =>
                {
                    b.Property<int>("Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Role_Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Role_Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Role_Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Role_Id = 2,
                            RoleName = "Consumer"
                        });
                });

            modelBuilder.Entity("Cinema.Data.Entities.Rooms", b =>
                {
                    b.Property<int>("Room_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Room_Id"));

                    b.Property<byte>("Capacity")
                        .HasColumnType("tinyint");

                    b.Property<int>("Cinema_Id")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Room_Id");

                    b.HasIndex("Cinema_Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Room_Id = 1,
                            Capacity = (byte)25,
                            Cinema_Id = 4,
                            RoomName = "IMAX Lounge"
                        },
                        new
                        {
                            Room_Id = 2,
                            Capacity = (byte)25,
                            Cinema_Id = 1,
                            RoomName = "IMAX Lounge"
                        },
                        new
                        {
                            Room_Id = 3,
                            Capacity = (byte)25,
                            Cinema_Id = 1,
                            RoomName = "VIP Lounge"
                        },
                        new
                        {
                            Room_Id = 4,
                            Capacity = (byte)25,
                            Cinema_Id = 2,
                            RoomName = "A Lounge"
                        },
                        new
                        {
                            Room_Id = 5,
                            Capacity = (byte)25,
                            Cinema_Id = 3,
                            RoomName = "B Lounge"
                        });
                });

            modelBuilder.Entity("Cinema.Data.Entities.Seats", b =>
                {
                    b.Property<int>("Seat_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Seat_Id"));

                    b.Property<byte>("Number")
                        .HasColumnType("tinyint");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Seat_Id");

                    b.HasIndex("Room_Id");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Seat_Id = 1,
                            Number = (byte)1,
                            Room_Id = 1,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 2,
                            Number = (byte)2,
                            Room_Id = 1,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 3,
                            Number = (byte)3,
                            Room_Id = 1,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 4,
                            Number = (byte)4,
                            Room_Id = 1,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 5,
                            Number = (byte)5,
                            Room_Id = 1,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 6,
                            Number = (byte)1,
                            Room_Id = 1,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 7,
                            Number = (byte)2,
                            Room_Id = 1,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 8,
                            Number = (byte)3,
                            Room_Id = 1,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 9,
                            Number = (byte)4,
                            Room_Id = 1,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 10,
                            Number = (byte)5,
                            Room_Id = 1,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 11,
                            Number = (byte)1,
                            Room_Id = 1,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 12,
                            Number = (byte)2,
                            Room_Id = 1,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 13,
                            Number = (byte)3,
                            Room_Id = 1,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 14,
                            Number = (byte)4,
                            Room_Id = 1,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 15,
                            Number = (byte)5,
                            Room_Id = 1,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 16,
                            Number = (byte)1,
                            Room_Id = 1,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 17,
                            Number = (byte)2,
                            Room_Id = 1,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 18,
                            Number = (byte)3,
                            Room_Id = 1,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 19,
                            Number = (byte)4,
                            Room_Id = 1,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 20,
                            Number = (byte)5,
                            Room_Id = 1,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 21,
                            Number = (byte)1,
                            Room_Id = 1,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 22,
                            Number = (byte)2,
                            Room_Id = 1,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 23,
                            Number = (byte)3,
                            Room_Id = 1,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 24,
                            Number = (byte)4,
                            Room_Id = 1,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 25,
                            Number = (byte)5,
                            Room_Id = 1,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 26,
                            Number = (byte)1,
                            Room_Id = 2,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 27,
                            Number = (byte)2,
                            Room_Id = 2,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 28,
                            Number = (byte)3,
                            Room_Id = 2,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 29,
                            Number = (byte)4,
                            Room_Id = 2,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 30,
                            Number = (byte)5,
                            Room_Id = 2,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 31,
                            Number = (byte)1,
                            Room_Id = 2,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 32,
                            Number = (byte)2,
                            Room_Id = 2,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 33,
                            Number = (byte)3,
                            Room_Id = 2,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 34,
                            Number = (byte)4,
                            Room_Id = 2,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 35,
                            Number = (byte)5,
                            Room_Id = 2,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 36,
                            Number = (byte)1,
                            Room_Id = 2,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 37,
                            Number = (byte)2,
                            Room_Id = 2,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 38,
                            Number = (byte)3,
                            Room_Id = 2,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 39,
                            Number = (byte)4,
                            Room_Id = 2,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 40,
                            Number = (byte)5,
                            Room_Id = 2,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 41,
                            Number = (byte)1,
                            Room_Id = 2,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 42,
                            Number = (byte)2,
                            Room_Id = 2,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 43,
                            Number = (byte)3,
                            Room_Id = 2,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 44,
                            Number = (byte)4,
                            Room_Id = 2,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 45,
                            Number = (byte)5,
                            Room_Id = 2,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 46,
                            Number = (byte)1,
                            Room_Id = 2,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 47,
                            Number = (byte)2,
                            Room_Id = 2,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 48,
                            Number = (byte)3,
                            Room_Id = 2,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 49,
                            Number = (byte)4,
                            Room_Id = 2,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 50,
                            Number = (byte)5,
                            Room_Id = 2,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 51,
                            Number = (byte)1,
                            Room_Id = 3,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 52,
                            Number = (byte)2,
                            Room_Id = 3,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 53,
                            Number = (byte)3,
                            Room_Id = 3,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 54,
                            Number = (byte)4,
                            Room_Id = 3,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 55,
                            Number = (byte)5,
                            Room_Id = 3,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 56,
                            Number = (byte)1,
                            Room_Id = 3,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 57,
                            Number = (byte)2,
                            Room_Id = 3,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 58,
                            Number = (byte)3,
                            Room_Id = 3,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 59,
                            Number = (byte)4,
                            Room_Id = 3,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 60,
                            Number = (byte)5,
                            Room_Id = 3,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 61,
                            Number = (byte)1,
                            Room_Id = 3,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 62,
                            Number = (byte)2,
                            Room_Id = 3,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 63,
                            Number = (byte)3,
                            Room_Id = 3,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 64,
                            Number = (byte)4,
                            Room_Id = 3,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 65,
                            Number = (byte)5,
                            Room_Id = 3,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 66,
                            Number = (byte)1,
                            Room_Id = 3,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 67,
                            Number = (byte)2,
                            Room_Id = 3,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 68,
                            Number = (byte)3,
                            Room_Id = 3,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 69,
                            Number = (byte)4,
                            Room_Id = 3,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 70,
                            Number = (byte)5,
                            Room_Id = 3,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 71,
                            Number = (byte)1,
                            Room_Id = 3,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 72,
                            Number = (byte)2,
                            Room_Id = 3,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 73,
                            Number = (byte)3,
                            Room_Id = 3,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 74,
                            Number = (byte)4,
                            Room_Id = 3,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 75,
                            Number = (byte)5,
                            Room_Id = 3,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 76,
                            Number = (byte)1,
                            Room_Id = 4,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 77,
                            Number = (byte)2,
                            Room_Id = 4,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 78,
                            Number = (byte)3,
                            Room_Id = 4,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 79,
                            Number = (byte)4,
                            Room_Id = 4,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 80,
                            Number = (byte)5,
                            Room_Id = 4,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 81,
                            Number = (byte)1,
                            Room_Id = 4,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 82,
                            Number = (byte)2,
                            Room_Id = 4,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 83,
                            Number = (byte)3,
                            Room_Id = 4,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 84,
                            Number = (byte)4,
                            Room_Id = 4,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 85,
                            Number = (byte)5,
                            Room_Id = 4,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 86,
                            Number = (byte)1,
                            Room_Id = 4,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 87,
                            Number = (byte)2,
                            Room_Id = 4,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 88,
                            Number = (byte)3,
                            Room_Id = 4,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 89,
                            Number = (byte)4,
                            Room_Id = 4,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 90,
                            Number = (byte)5,
                            Room_Id = 4,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 91,
                            Number = (byte)1,
                            Room_Id = 4,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 92,
                            Number = (byte)2,
                            Room_Id = 4,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 93,
                            Number = (byte)3,
                            Room_Id = 4,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 94,
                            Number = (byte)4,
                            Room_Id = 4,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 95,
                            Number = (byte)5,
                            Room_Id = 4,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 96,
                            Number = (byte)1,
                            Room_Id = 4,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 97,
                            Number = (byte)2,
                            Room_Id = 4,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 98,
                            Number = (byte)3,
                            Room_Id = 4,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 99,
                            Number = (byte)4,
                            Room_Id = 4,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 100,
                            Number = (byte)5,
                            Room_Id = 4,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 101,
                            Number = (byte)1,
                            Room_Id = 5,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 102,
                            Number = (byte)2,
                            Room_Id = 5,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 103,
                            Number = (byte)3,
                            Room_Id = 5,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 104,
                            Number = (byte)4,
                            Room_Id = 5,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 105,
                            Number = (byte)5,
                            Room_Id = 5,
                            Row = "A"
                        },
                        new
                        {
                            Seat_Id = 106,
                            Number = (byte)1,
                            Room_Id = 5,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 107,
                            Number = (byte)2,
                            Room_Id = 5,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 108,
                            Number = (byte)3,
                            Room_Id = 5,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 109,
                            Number = (byte)4,
                            Room_Id = 5,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 110,
                            Number = (byte)5,
                            Room_Id = 5,
                            Row = "B"
                        },
                        new
                        {
                            Seat_Id = 111,
                            Number = (byte)1,
                            Room_Id = 5,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 112,
                            Number = (byte)2,
                            Room_Id = 5,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 113,
                            Number = (byte)3,
                            Room_Id = 5,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 114,
                            Number = (byte)4,
                            Room_Id = 5,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 115,
                            Number = (byte)5,
                            Room_Id = 5,
                            Row = "C"
                        },
                        new
                        {
                            Seat_Id = 116,
                            Number = (byte)1,
                            Room_Id = 5,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 117,
                            Number = (byte)2,
                            Room_Id = 5,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 118,
                            Number = (byte)3,
                            Room_Id = 5,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 119,
                            Number = (byte)4,
                            Room_Id = 5,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 120,
                            Number = (byte)5,
                            Room_Id = 5,
                            Row = "D"
                        },
                        new
                        {
                            Seat_Id = 121,
                            Number = (byte)1,
                            Room_Id = 5,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 122,
                            Number = (byte)2,
                            Room_Id = 5,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 123,
                            Number = (byte)3,
                            Room_Id = 5,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 124,
                            Number = (byte)4,
                            Room_Id = 5,
                            Row = "E"
                        },
                        new
                        {
                            Seat_Id = 125,
                            Number = (byte)5,
                            Room_Id = 5,
                            Row = "E"
                        });
                });

            modelBuilder.Entity("Cinema.Data.Entities.Showtimes", b =>
                {
                    b.Property<int>("Showtime_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Showtime_Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("Movie_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Room_Id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ShowDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Showtime_Id");

                    b.HasIndex("Movie_Id");

                    b.HasIndex("Room_Id");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            Showtime_Id = 1,
                            EndTime = new TimeOnly(20, 12, 0),
                            Movie_Id = 1,
                            Price = 4.99m,
                            Room_Id = 5,
                            ShowDate = new DateOnly(2026, 7, 22),
                            StartTime = new TimeOnly(17, 35, 0)
                        },
                        new
                        {
                            Showtime_Id = 2,
                            EndTime = new TimeOnly(23, 14, 0),
                            Movie_Id = 3,
                            Price = 3.99m,
                            Room_Id = 4,
                            ShowDate = new DateOnly(2026, 7, 23),
                            StartTime = new TimeOnly(21, 0, 0)
                        },
                        new
                        {
                            Showtime_Id = 3,
                            EndTime = new TimeOnly(22, 25, 0),
                            Movie_Id = 2,
                            Price = 4.99m,
                            Room_Id = 3,
                            ShowDate = new DateOnly(2026, 7, 25),
                            StartTime = new TimeOnly(19, 55, 0)
                        },
                        new
                        {
                            Showtime_Id = 4,
                            EndTime = new TimeOnly(17, 3, 0),
                            Movie_Id = 4,
                            Price = 6.29m,
                            Room_Id = 2,
                            ShowDate = new DateOnly(2026, 7, 24),
                            StartTime = new TimeOnly(15, 5, 0)
                        },
                        new
                        {
                            Showtime_Id = 5,
                            EndTime = new TimeOnly(22, 11, 0),
                            Movie_Id = 5,
                            Price = 7.59m,
                            Room_Id = 5,
                            ShowDate = new DateOnly(2026, 7, 22),
                            StartTime = new TimeOnly(20, 25, 0)
                        });
                });

            modelBuilder.Entity("Cinema.Data.Entities.TransactionSeats", b =>
                {
                    b.Property<int>("TransactionSeat_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionSeat_Id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Seat_Id")
                        .HasColumnType("int");

                    b.Property<int>("Transaction_Id")
                        .HasColumnType("int");

                    b.HasKey("TransactionSeat_Id");

                    b.HasIndex("Seat_Id");

                    b.HasIndex("Transaction_Id");

                    b.ToTable("TransactionSeats");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Transactions", b =>
                {
                    b.Property<int>("Transaction_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Transaction_Id"));

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Showtime_Id")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.HasKey("Transaction_Id");

                    b.HasIndex("Showtime_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Users", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("User_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role_Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Fran@mail.com",
                            FullName = "Francesco Totti",
                            PasswordHash = "$argon2id$v=19$m=65536,t=4,p=8$aFQxVzBGWEQwVnprM2lHbw$crbzfKlT7lflD3QFxH0LSUGapiuoY3Nu2an3OvFvXbQ",
                            Role_Id = 2,
                            Username = "Fran34J"
                        },
                        new
                        {
                            User_Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Rob@mail.com",
                            FullName = "Roberto Baggio",
                            PasswordHash = "$argon2id$v=19$m=65536,t=4,p=8$dHlRS1M2Qng2eVl6a016eg$OoY2yrwFm6MC0wGW5cOWzmFloe9i9/cKb+wUeTl1Mik",
                            Role_Id = 1,
                            Username = "Rob94"
                        });
                });

            modelBuilder.Entity("Cinema.Data.Entities.Rooms", b =>
                {
                    b.HasOne("Cinema.Data.Entities.Cinemas", "Cinema")
                        .WithMany("rooms")
                        .HasForeignKey("Cinema_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Seats", b =>
                {
                    b.HasOne("Cinema.Data.Entities.Rooms", "Room")
                        .WithMany("seats")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Showtimes", b =>
                {
                    b.HasOne("Cinema.Data.Entities.Movies", "Movie")
                        .WithMany("showtimes")
                        .HasForeignKey("Movie_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Data.Entities.Rooms", "Room")
                        .WithMany("showtimes")
                        .HasForeignKey("Room_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Cinema.Data.Entities.TransactionSeats", b =>
                {
                    b.HasOne("Cinema.Data.Entities.Seats", "Seat")
                        .WithMany("transactionSeats")
                        .HasForeignKey("Seat_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Data.Entities.Transactions", "Transaction")
                        .WithMany("transactionSeats")
                        .HasForeignKey("Transaction_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Transactions", b =>
                {
                    b.HasOne("Cinema.Data.Entities.Showtimes", "Showtime")
                        .WithMany("transactions")
                        .HasForeignKey("Showtime_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema.Data.Entities.Users", "User")
                        .WithMany("transactions")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Users", b =>
                {
                    b.HasOne("Cinema.Data.Entities.Roles", "Role")
                        .WithMany("users")
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Cinemas", b =>
                {
                    b.Navigation("rooms");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Movies", b =>
                {
                    b.Navigation("showtimes");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Roles", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Rooms", b =>
                {
                    b.Navigation("seats");

                    b.Navigation("showtimes");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Seats", b =>
                {
                    b.Navigation("transactionSeats");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Showtimes", b =>
                {
                    b.Navigation("transactions");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Transactions", b =>
                {
                    b.Navigation("transactionSeats");
                });

            modelBuilder.Entity("Cinema.Data.Entities.Users", b =>
                {
                    b.Navigation("transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
